// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOHh1rSshkK5nDBy7wmeXADlYyumsJ2mk',
    appId: '1:997578479413:web:e1f323ea20ddb65fb7de7c',
    messagingSenderId: '997578479413',
    projectId: 'mydailyapp-8cb4b',
    authDomain: 'mydailyapp-8cb4b.firebaseapp.com',
    storageBucket: 'mydailyapp-8cb4b.appspot.com',
    measurementId: 'G-LN9B1T9HBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCBe3pZ5eFDCYDqomeoDFF1gNXpfd3r8Y',
    appId: '1:997578479413:android:e4899373ecc8dc9ab7de7c',
    messagingSenderId: '997578479413',
    projectId: 'mydailyapp-8cb4b',
    storageBucket: 'mydailyapp-8cb4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvYHaf77ewskXJWNLd_haCq3fUK2dSfk',
    appId: '1:997578479413:ios:08eb47d8ba081684b7de7c',
    messagingSenderId: '997578479413',
    projectId: 'mydailyapp-8cb4b',
    storageBucket: 'mydailyapp-8cb4b.appspot.com',
    iosBundleId: 'com.example.mydailyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZvYHaf77ewskXJWNLd_haCq3fUK2dSfk',
    appId: '1:997578479413:ios:08eb47d8ba081684b7de7c',
    messagingSenderId: '997578479413',
    projectId: 'mydailyapp-8cb4b',
    storageBucket: 'mydailyapp-8cb4b.appspot.com',
    iosBundleId: 'com.example.mydailyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOHh1rSshkK5nDBy7wmeXADlYyumsJ2mk',
    appId: '1:997578479413:web:be9ee385e7a097f7b7de7c',
    messagingSenderId: '997578479413',
    projectId: 'mydailyapp-8cb4b',
    authDomain: 'mydailyapp-8cb4b.firebaseapp.com',
    storageBucket: 'mydailyapp-8cb4b.appspot.com',
    measurementId: 'G-Z4N1LFPPV3',
  );

}